title: BRB Open Data Visualization
description: Visualizing banking data from the Bank of the Republic of Burundi
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima

# Sass settings
sass:
  style: compressed
  implementation: sass-embedded
  sass_dir: _sass

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
  - .sass-cache/
  - .git/
  - .github/
  - node_modules/
  - vendor/

# Disable unnecessary features
show_excerpts: false
plugins: [] # Disable all plugins
feed:
  enabled: false # Explicitly disable feed generation
