# config/sources.yml
# For each source, specify:
#   name: a key for this source (used for local subdir or logging)
#   url: either a direct link to the Excel file (ending in .xls[x])
#        or a page URL where the Excel link must be discovered
#   pattern: (optional) if url is a page, a regex to match the Excel filename in <a href=...>
#   local_subdir: where under data/raw/ to save files
sources:
  importation_countries:
    url: "https://www.brb.bi/node/477"
    local_subdir: "data/raw/importation_countries"
    pattern: "IV\\.5\\.Importations.*\\.(xlsx|xls)"

  importation_categories:
    url: "https://www.brb.bi/node/343"
    local_subdir: "data/raw/importation_categories"
    pattern: "IV\\.2\\.Importations_par_rubrique.*\\.(xlsx|xls)"
