name: Monthly ETL Taux Inflation Job

on:
  schedule:
    - cron: '0 0 1 * *'  # This runs the job at 00:00 on the 1st of every month.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3'

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run ETL script
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        RELATIVE_PATH: ${{ secrets.RELATIVE_PATH }}
      run: python etl_taux_inflation.py  # Replace with the name of your ETL script file
