name: Chart and Dashboard Creation Job
on:
  schedule:
    - cron: '0 5 1 * *' # Run at 05:00 a.m. on the first day of every month

jobs:
  dashboard:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    # Step to copy the CSV file from the ETL job artifacts
    - name: Copy CSV file
      uses: actions/download-artifact@v2
      with:
        name: etl-artifact  # Replace with the actual name of the ETL job artifact
        path: data  # Specify the path where the CSV file was saved in the ETL job

    - name: Run dashboard creation job
      run: python python_script.py
